<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file is part of the Meeds project (https://meeds.io/).

 Copyright (C) 2020 - 2025 Meeds Association contact@meeds.io

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 3 of the License, or (at your option) any later version.
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program; if not, write to the Free Software Foundation,
 Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <artifactId>maven-parent-pom</artifactId>
    <groupId>io.meeds</groupId>
    <version>29-M02</version>
  </parent>
  
  <groupId>io.meeds.gatein.sso</groupId>
  <artifactId>sso-parent</artifactId>
  <version>7.2.0-meed-20260519</version>
  <packaging>pom</packaging>
  
  
  <name>Gatein - Single Sign On Integration</name>
  <description>GateIn Single Sign On Integration</description>
  
  <scm>
    <connection>scm:git:git://github.com/meeds-io/gatein-sso.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/meeds-io/gatein-sso.git</developerConnection>
    <url>https://github.com/meeds-io/gatein-sso</url>
    <tag>7.2.0-meed-20260519</tag>
  </scm>

  <modules>
    <module>sso-agent</module>
    <module>sso-saml-plugin</module>
  </modules>

  <properties>
    <io.meeds.ws.version>7.2.0-meed-20260519</io.meeds.ws.version>
    <!-- Sonar properties -->
    <sonar.organization>meeds-io</sonar.organization>
    
  </properties>
  
  <dependencyManagement>
    <dependencies>
      
      <!-- Import dependency management configuration -->
      <dependency>
        <groupId>io.meeds.ws</groupId>
        <artifactId>ws-parent</artifactId>
        <version>${io.meeds.ws.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <!-- Current project artifacts -->
      <dependency>
        <groupId>io.meeds.gatein.sso</groupId>
        <artifactId>sso-agent</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.meeds.gatein.sso</groupId>
        <artifactId>sso-saml-plugin</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <finalName>${project.artifactId}</finalName>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-patch-plugin</artifactId>
          <version>1.2</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
  <!-- This profile is used to allow github action to build branches. The github action is used for sonar analysis -->
  <profiles>
    <profile>
      <id>project-repositories</id>
      <activation>
        <property>
          <name>!skip-project-repositories</name>
        </property>
      </activation>
      <repositories>
        <repository>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
          <id>repository.exoplatform.org</id>
          <url>https://repository.exoplatform.org/public</url>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
          <id>repository.exoplatform.org</id>
          <url>https://repository.exoplatform.org/public</url>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
</project>
